name: namefully
version: 0.1.8
description: >-
  A Dart utility for handling person names in a particular order, way, or shape.
repository: https://github.com/ralflorent/namefully-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.0
