name: namefully
version: 0.1.0-beta.1
description: A Dart utility for handling person names.
repository: https://github.com/ralflorent/namefully-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.0
  test_coverage: ^0.5.0
