name: namefully
description: A Dart utility for handling person names.
version: 0.0.1
homepage: https://namefully.dev
repository: https://github.com/ralflorent/namefully-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.0
