name: namefully
version: 0.1.5
description: >-
  A Dart utility for handling person names in a particular order, way, or shape.
repository: https://github.com/ralflorent/namefully-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.17.0
